# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Install git and wget
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git wget

# Clone the MiniGPT-4 repository
RUN git clone https://github.com/DanielTea/MiniGPT-4.git /app

# Download the pretrained model file
RUN wget -O pretrained_minigpt4_7b.pth https://huggingface.co/wangrongsheng/MiniGPT4-7B/resolve/main/pretrained_minigpt4_7b.pth

# Copy the requirements file into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt and additional packages
RUN pip install --trusted-host pypi.python.org -r requirements.txt && \
    pip install h5py typing-extensions wheel && \
    pip install git+https://github.com/huggingface/transformers.git -U

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run the application when the container launches
CMD ["python", "demo.py"]